---
version: '3.7'
services:
  ## MySQL Docker Compose Config
  mysql:
    container_name: mysql
    image: mysql_db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/data/db

  ## Eureka Service
  registry-server:
    image: microservices/registry-service:latest
    container_name: registry-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    ## Identity Service
  identity-service:
    image: microservices/identity-service:latest
    container_name: identity-service
    ports:
        - "8081:8081"
    environment:
        - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: microservices/manufacture-gateway:latest
    container_name: manufacture-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - registry-service


  ## Order Service Docker Compose Config
  order-service:
    image: microservices/order-service:latest
    container_name: order-service
    ports:
    - "8082:8082"
    expose:
    - "8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry-service
      - api-gateway

   ## App Service Docker Compose Config
  app-service:
    image: microservices/app-service:latest
    container_name: app-service
    ports:
      - "8085:8085"
    expose:
      - "8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry-service
      - api-gateway



