---
version: '3.7'
services:
  ## MySQL Docker Compose Config
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: manufacture


  ## Eureka Service
  registry-service:
    image: microservices/registry-service:0.0.1-SNAPSHOT
    container_name: registry-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    ## Identity Service
  identity-service:
    image: microservices/identity-service:0.0.1-SNAPSHOT
    container_name: identity-service
    ports:
        - "8081:8081"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    depends_on:
          - manufacture-gateway
          - registry-service

  manufacture-gateway:
    image: microservices/manufacture-gateway:0.0.1-SNAPSHOT
    container_name: manufacture-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - registry-service


  ## Order Service Docker Compose Config
  order-service:
    image: microservices/order-service:0.0.1-SNAPSHOT
    container_name: order-service
    ports:
    - "8082:8082"
    expose:
    - "8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry-service
      - manufacture-gateway


   ## App Service Docker Compose Config
  manufacture-app:
    image: microservices/manufacture-app:0.0.1-SNAPSHOT
    container_name: manufacture-app
    ports:
      - "8085:8085"
    expose:
      - "8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry-service
      - manufacture-gateway



